### ISSUE TITLE
Node 0.12.6 Not Found

### ISSUE THREAD

**Issue by michaelnisi** [joyent/pkgsrc-joyent#23]
Why does `pkgin` list Node 0.12.6 but fails to install it?

```
# pkgin up
database for http://pkgsrc.joyent.com/packages/SmartOS/2015Q2/x86_64/All is up-to-date
# pkgin se node | grep 0.12.6
nodejs-0.12.6        V8 JavaScript for clients and servers
# pkgin in nodejs-0.12.6
…
pkgin: http://pkgsrc.joyent.com/packages/SmartOS/2015Q2/x86_64/All/nodejs-0.12.6.tgz: Not Found
```

**Comment by jperkin** [comment]
Not entirely sure why it disappeared in the first place, but due to the way our publishing system works, since it is no longer the current 0.12.x package then it wouldn't be picked up by subsequent rsyncs - i.e. we only rsync the current set of packages, and avoid --delete to ensure that legacy packages remain.

For now I've manually copied it up, it'll take about 15 minutes to sync around the mirrors.  My best guess is that the rsync after building 0.12.6 was interrupted before it could be copied, and the subsequent build updated nodejs to 0.12.7 so .6 was never noticed and retried.

It may be possible for us to catch issues like this, but in the meantime the workaround would simply be to use the latest package rather than relying on the older versions remaining available.

Thanks for the report.

**Comment by michaelnisi** [comment]
Thanks for the quick response.
